name: sales_forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.23
  
  # Core data science libraries
  - pandas=1.5.3
  - numpy=1.26.4
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - statsmodels=0.14.4
  - sktime=0.36.1
  
  # Machine learning
  - xgboost=2.1.4
  - shap=0.48.0
  
  # Visualization
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - plotly=6.1.2
  
  # Data processing
  - pyarrow=20.0.0
  - openpyxl=3.1.5
  - make
  
  # Validation
  - pandera=0.22.1
  
  # Jupyter/IPython
  - ipython=8.18.1
  - ipykernel=6.29.5
  - jupyter_client=8.6.3
  
  # Web apps
  - streamlit=1.45.1
  
  # Development tools
  - conda-lock=3.0.3
  
  # Utilities
  - joblib=1.4.2
  
  # Pip packages
  - pip
  - pip:
    - prophet==1.1.7
    - altair-ally==0.1.1
    - vega-datasets==0.9.0